# Generated by Django 4.1.2 on 2022-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
    ]
